services:
  frontend:
    build:
      context: ./frontend
    image: ghcr.io/mertozqq/film-react-nest-frontend:latest
    volumes:
      - frontend_dist:/frontend-dist
    healthcheck:
      test: ["CMD-SHELL", "test -f /frontend-dist/index.html"]
      interval: 2s
      timeout: 2s
      retries: 10
    networks:
      - app_network

  backend:
    build:
      context: ./backend
    image: ghcr.io/mertozqq/film-react-nest-backend:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DATABASE_DRIVER: postgres
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/app_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('net').connect(3000, '127.0.0.1').on('connect', () => process.exit(0)).on('error', () => process.exit(1))",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app_network

  nginx:
    build:
      context: ./nginx
    image: ghcr.io/mertozqq/film-react-nest-nginx:latest
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    ports:
      - "80:80"
    volumes:
      - frontend_dist:/usr/share/nginx/html:ro
    networks:
      - app_network

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - app_network

volumes:
  frontend_dist:
  postgres_data:
  pgadmin_data:

networks:
  app_network:
    driver: bridge
